/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.gui;

import com.placeholder.PlaceHolder;
import static java.awt.Event.ENTER;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.Document;
import mx.itson.entidades.Usuario;
import mx.itson.implementacion.UsuarioImp;
import mx.itson.instancias.InstanciaConexion;
import mx.itson.instancias.InstanciaLogin;
import mx.itson.interfaces.UsuarioInt;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

    private static InstanciaLogin login = InstanciaLogin.getInstanciaLogin();
    private static InstanciaConexion conexion = InstanciaConexion.getInstanciaConexion();
    public static Usuario usuario;
    UsuarioInt usrImp = new UsuarioImp();

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mx/itson/items/iconotorti.png"));
        setIconImage(icon);
        this.setTitle("Sistema Punto de Venta Tortillería - Login");
        PlaceHolder holder = new PlaceHolder(usuarioTextField, "Ingrese correo electrónico aquí");
        PlaceHolder holder1 = new PlaceHolder(contrasenaTextField, "Contraseña");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        usuarioTextField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        contrasenaTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label2 = new java.awt.Label();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 167, 131));
        setResizable(false);

        panel1.setBackground(new java.awt.Color(0, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("TORTILLERÍA");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 40));

        usuarioTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usuarioTextField.setForeground(new java.awt.Color(204, 204, 204));
        usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextFieldActionPerformed(evt);
            }
        });
        panel1.add(usuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 249, 37));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOG IN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 249, 40));

        contrasenaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contrasenaTextFieldKeyReleased(evt);
            }
        });
        panel1.add(contrasenaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 249, 37));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de usuario");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        panel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 449, 10, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/LOGOTORTILLERIA_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, 200));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("SISTEMA PUNTO DE VENTA");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usuarioTextFieldActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String nombreUsuario = usuarioTextField.getText();
        String contrasena = new String(contrasenaTextField.getPassword());
        String tipo;
        if (login.Login(nombreUsuario, contrasena, conexion.conexion())) {
            System.out.println("Login correcto");
            errorLabel.setText("");

            try {

                usuario = usrImp.buscar_nombreUsuario(nombreUsuario).get(0);
                //JFrame menuPrincipal = InstanciaVentana.getMenuPrincipal();
                if (usuario.getTipo().equals("Administrador")) {
                    ComprasAdmi f = new ComprasAdmi();
                    f.setVisible(true);
                } else {
                    ComprasUsuario vu = new ComprasUsuario();
//                    ProductosUsuario pu = new ProductosUsuario();
//                    VentasUsuario cu = new VentasUsuario();
//                    vu.lbUsuarioSesion.setText(usuarioTextField.getText());
//                    pu.lbUsuarioSesion.setText(usuarioTextField.getText());
//                    cu.lbUsuarioSesion.setText(usuarioTextField.getText());
                    vu.setVisible(true);

                }
            } catch (SQLException e) {
                System.out.println("Error: " + e.getMessage());
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                this.setVisible(false);
            }
        } else {
            System.out.println("Login incorrecto");
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecto, pruebe de nuevo", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void contrasenaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contrasenaTextFieldKeyReleased

    }//GEN-LAST:event_contrasenaTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField contrasenaTextField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Panel panel1;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
