/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.gui;

import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.entidades.Producto;
import mx.itson.implementacion.ProductoImp;
import mx.itson.interfaces.ProductoInt;

/**
 *
 * @author Dell
 */
public class ProductosUsuario extends javax.swing.JFrame {

    ProductoInt proImp = new ProductoImp();
    DefaultTableModel modelo;
    String[] titulos = {"Id", "Producto", "Precio"};
    List<Producto> productos;
    public static Producto pro;

    /**
     * Creates new form ComprasUsuario
     */
    public ProductosUsuario() throws IOException {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mx/itson/items/iconotorti.png"));
        setIconImage(icon);
        this.setTitle("Productos usuario");
//        PlaceHolder holder1 = new PlaceHolder(txtNombre, "Nombre del producto");
//        PlaceHolder holder3 = new PlaceHolder(txtPrecio, "Precio del producto");
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        tbProductos.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        productosl();
    }

    public void productosl() {
        try {
            productos = proImp.lista_productos();
            for (Producto pro : productos) {
                Object[] o = new Object[4];
                o[0] = pro.getId();
                o[1] = pro.getProducto();
                o[2] = "$ " + pro.getPrecio();

                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCerrarSesion1 = new javax.swing.JButton();
        btnProveedor1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbUsuarioSesion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1322, 720));
        jPanel1.setLayout(null);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/ventas.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas);
        btnVentas.setBounds(300, 80, 230, 80);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/compra.png"))); // NOI18N
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompra);
        btnCompra.setBounds(540, 80, 230, 80);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/productos.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos);
        btnProductos.setBounds(780, 80, 230, 80);

        btnCerrarSesion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/cerrar-sesion.png"))); // NOI18N
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion1);
        btnCerrarSesion1.setBounds(1090, 10, 200, 50);

        btnProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/proveedores.png"))); // NOI18N
        btnProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedor1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedor1);
        btnProveedor1.setBounds(1020, 110, 190, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SESIÓN ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(870, 30, 100, 30);

        lbUsuarioSesion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuarioSesion.setText("USUARIO");
        jPanel1.add(lbUsuarioSesion);
        lbUsuarioSesion.setBounds(970, 30, 340, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tbProductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "producto", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbProductos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(310, 240, 790, 440);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTOS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 180, 1320, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/fondo-tortilleria.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        try {
            VentasUsuario fl = new VentasUsuario();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VentasUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        try {
            ComprasUsuario fl = new ComprasUsuario();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ComprasUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        try {
            ProductosUsuario fl = new ProductosUsuario();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ProductosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        Login fl = new Login();
        this.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, "Sesión cerrada. Vuelve pronto.");
        fl.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed

    private void btnProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedor1ActionPerformed
        ProveedorUsuario fl = new ProveedorUsuario();
        this.setVisible(false);
        fl.setVisible(true);
    }//GEN-LAST:event_btnProveedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductosUsuario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ProductosUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedor1;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbUsuarioSesion;
    private javax.swing.JTable tbProductos;
    // End of variables declaration//GEN-END:variables
}
