/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.gui;

import com.placeholder.PlaceHolder;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.entidades.Producto;
import static mx.itson.gui.AdminUsuariosAdmi.usuario;
import mx.itson.implementacion.ProductoImp;
import mx.itson.interfaces.ProductoInt;

/**
 *
 * @author Dell
 */
public class ProductosAdmi extends javax.swing.JFrame {

    ProductoInt proImp = new ProductoImp();
    DefaultTableModel modelo;
    String[] titulos = {"Id", "Producto", "Precio"};
    List<Producto> productos;
    public static Producto pro;

    /**
     * Creates new form ComprasUsuario
     */
    public ProductosAdmi() throws IOException {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mx/itson/items/iconotorti.png"));
        setIconImage(icon);
        this.setTitle("Productos admin.");
        PlaceHolder holder1 = new PlaceHolder(txtNombre, "Nombre del producto");
        PlaceHolder holder3 = new PlaceHolder(txtPrecio, "Precio del producto");
        setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        tbProductos.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        productosl();
    }

    public void productosl() {
        try {
            productos = proImp.lista_productos();
            for (Producto pro : productos) {
                Object[] o = new Object[4];
                o[0] = pro.getId();
                o[1] = pro.getProducto();
                o[2] = "$ " + pro.getPrecio();

                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbUsuarioSesion = new javax.swing.JLabel();
        btnCompra = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnProveedor1 = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnAdmiUsuarios = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1322, 720));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SESIÓN ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(870, 30, 100, 30);

        lbUsuarioSesion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbUsuarioSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuarioSesion.setText("ADMINISTRADOR");
        jPanel1.add(lbUsuarioSesion);
        lbUsuarioSesion.setBounds(970, 30, 340, 30);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/compra.png"))); // NOI18N
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompra);
        btnCompra.setBounds(260, 80, 230, 80);

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/ventas.png"))); // NOI18N
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas);
        btnVentas.setBounds(20, 80, 230, 80);

        btnProveedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/proveedores.png"))); // NOI18N
        btnProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedor1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedor1);
        btnProveedor1.setBounds(30, 180, 200, 50);

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/productos.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos);
        btnProductos.setBounds(500, 80, 230, 80);

        btnAdmiUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/admin-usuario.png"))); // NOI18N
        btnAdmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmiUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmiUsuarios);
        btnAdmiUsuarios.setBounds(740, 80, 310, 80);

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/inventario.png"))); // NOI18N
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario);
        btnInventario.setBounds(1060, 80, 230, 80);

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/cerrar-sesion.png"))); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(1090, 180, 200, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Introduce los datos del producto");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/agregar.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/quitar.png"))); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/editar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 240, 450, 440);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        tbProductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "producto", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbProductos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(510, 240, 790, 440);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTOS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 180, 1320, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/items/fondo-tortilleria.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1330, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        try {
            ProductosAdmi fl = new ProductosAdmi();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ProductosAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnAdmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmiUsuariosActionPerformed
        try {
            AdminUsuariosAdmi fl = new AdminUsuariosAdmi();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminUsuariosAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdmiUsuariosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        try {
            InventarioAdmi fl = new InventarioAdmi();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(InventarioAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        try {
            VentasAdmi fl = new VentasAdmi();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VentasAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        try {
            ComprasAdmi fl = new ComprasAdmi();
            this.setVisible(false);
            fl.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ComprasAdmi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login fl = new Login();
        this.setVisible(false);
        JOptionPane.showMessageDialog(rootPane, "Sesión cerrada. Vuelve pronto.");
        fl.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (!tbProductos.getSelectionModel().isSelectionEmpty()) {
            pro = productos.get(tbProductos.getSelectedRow());
            EditarProducto ep = new EditarProducto();
            this.setVisible(false);
            ep.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtNombre.getText().isEmpty() || txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Los siguientes campos no pueden estar vacíos: \nProducto\nPrecio", "Datos incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Producto prodt = new Producto();
                prodt.setProducto(txtNombre.getText());
                prodt.setPrecio(Double.parseDouble(txtPrecio.getText()));
                ProductoInt proImp = new ProductoImp();
                if (proImp.Agregar(prodt)) {
                    JOptionPane.showMessageDialog(null, "Se registró el producto", "Producto registrado", JOptionPane.INFORMATION_MESSAGE);

                }

            } catch (Exception e) {
            }
        }
        modelo = new DefaultTableModel();
        tbProductos.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        productosl();
        txtNombre.setText("");
        txtPrecio.setText("");
        PlaceHolder holder1 = new PlaceHolder(txtNombre, "Nombre del producto");
        PlaceHolder holder3 = new PlaceHolder(txtPrecio, "Precio del producto");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed

        if (!tbProductos.getSelectionModel().isSelectionEmpty()) {
            pro = productos.get(tbProductos.getSelectedRow());
            if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el producto " + pro.getProducto() + "?", "Quitar producto", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
                try {
                    if (proImp.Eliminar(pro)) {
                        JOptionPane.showMessageDialog(null, "Se ha eliminado el producto con éxito", "Producto eliminado", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        tbProductos.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        productos = proImp.lista_productos();
                        for (Producto prodt : productos) {
                            Object[] o = new Object[4];
                            o[0] = prodt.getId();
                            o[1] = prodt.getProducto();
                            o[2] = prodt.getPrecio();
                            modelo.addRow(o);
                        }

                    }
                } catch (Exception e) {
                }
            }
        }
        modelo = new DefaultTableModel();
        tbProductos.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        productosl();
        txtNombre.setText("");
        txtPrecio.setText("");
        PlaceHolder holder1 = new PlaceHolder(txtNombre, "Nombre del producto");
        PlaceHolder holder3 = new PlaceHolder(txtPrecio, "Precio del producto");
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedor1ActionPerformed
        ProveedorAdmin fl = new ProveedorAdmin();
        this.setVisible(false);
        fl.setVisible(true);
    }//GEN-LAST:event_btnProveedor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductosAdmi().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ProductosAdmi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmiUsuarios;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedor1;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbUsuarioSesion;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
